### ISSUE TITLE
Porting to ESP32

### ISSUE THREAD

**Issue by serega404** [abhigkar/YHK-Cat-Thermal-Printer#2]
I noticed that you were looking for a solution for ESP 32, just like you, I ran into this problem and already planned to intercept BLE traffic using rpi zero w and wireshark, but I was lucky to find your repository. Are you planning to migrate any of the existing libraries for ESP 32 to our device? I also noticed that the [library](https://github.com/rnrobles/esc-thermal-printer-ble) it can send data to the device and scroll through paper, but it cannot draw, perhaps transferring this library will be very simple.

**Comment by abhigkar** [comment]
This specific Cat thermal printer does not follow the rules as the other do. The issue is with model is that this works on classic bluetooth (not the BLE) and accepts 1 bit image as input. The other accepts the commands, so I had to do reverse engineering. The library you shared is command based so it will not work with this printer.
